### ISSUE TITLE
Set up documentation to live on osome website

### ISSUE THREAD

**Issue by mr-devs** [osome-iu/top-FIBers#1]
This repository's main `README.md` still points to the documentation that lives on Matt's website: 
- [https://www.matthewdeverna.com/top-FIBers/](https://www.matthewdeverna.com/top-FIBers/)

It looks like I do not have access to the "Settings" page of this repository which would allow me to set this up. Can someone please take care of this?

From the "Pages" tab, you should be able to select something like the below.
---
![image](https://github.com/osome-iu/top-FIBers/assets/48068852/3909f151-922c-415b-9c10-4fa5d65d8fae)

**Comment by pasan04** [comment]
I added the updated documentation link.
