### ISSUE TITLE
Add links/notes for front-end repository

### ISSUE THREAD

**Issue by mr-devs** [osome-iu/top-FIBers#10]
I think that we talked about this a while back but I guess it fell through the cracks. Can you please add some links to the front-end repo in the docs?

For example please add links in the following sections: [here](https://github.com/osome-iu/top-FIBers/blob/567a891c594037c5fd94398188916248ad5f52c1/docs/README.md?plain=1#L9) (in the bullet list) and [here](https://github.com/osome-iu/top-FIBers/blob/567a891c594037c5fd94398188916248ad5f52c1/docs/code/overview.md?plain=1#L66) and [here](https://github.com/osome-iu/top-FIBers/blob/567a891c594037c5fd94398188916248ad5f52c1/docs/code/architecture.md?plain=1#L21).

I believe we spoke previously about keeping the front-end documentation separate from this repository so that things are not duplicated. So feel free to write whatever you think is best. Something that simply says, "Find the front-end code [here](https://www.example.com)." is more than enough from my perspective but the two repos should be connected

**Comment by pasan04** [comment]
I added the frontend repo links to these code documentation.
