### ISSUE TITLE
Add git line for iffy data files to monthly bash script

### ISSUE THREAD

**Issue by mr-devs** [osome-iu/top-FIBers#12]
We need to add a line to the monthly pipeline that backs up the latest iffy domains file to GitHub. I think the below will work but we will need to do some testing.

```
git add data/iffy_files/*; git commit -m 'add latest iffy file; git push
```

Not sure if this is better to add directly after the iffy list has been downloaded or at the end of the pipeline... 🤔 

> **NOTE:** We may want to make the above more specific. Right now it will add anything that is in there, which is a bit of overkill. We could instead be more specific about the file name. However, this would require getting the date right which would take some more effort.

**Comment by nick-c-liu** [comment]
I think it should be fine to add all.
The script has been tested. Added to the end of the pipeline so it won't affect other processes.
