### ISSUE TITLE
Double check how broken profile image links are handled

### ISSUE THREAD

**Issue by mr-devs** [osome-iu/top-FIBers#16]
Hi @pasan04!

Since the Twitter profile image links will no longer be updated (see #15), many of these profile image links will likely break over time. Can you please double-check that the front end can handle this? I guess the desired behavior would be to do what the Facebook tab does if the image link no longer works. Of course, we'd like to use the images if we can.

Let me know your thoughts when you can and feel free to close the issue as soon as you're confident this is handled.

Thanks!

**Comment by pasan04** [comment]
Sure. I will have a look into this and make the changes asap.

**Comment by pasan04** [comment]
I handled the broken photo link in twitter by adding the photo link as facebook did. It's in blue colored with white colored letter. ex - https://twitter.com/RobertKennedyJr
