### ISSUE TITLE
Improve logging: Print the permanent doi link for zenodo

### ISSUE THREAD

**Issue by mr-devs** [osome-iu/top-FIBers#19]
https://github.com/osome-iu/top-FIBers/blob/3ca1c097c64abde71a5c75e886346342e8c3bce8/scripts/update_zenodo.py#L81C45-L81C45

Right below this line, print the following logging message: `DOI permalink: https://doi.org/10.5281/zenodo.8205713`

This will make it easier to check the site each month when looking through the logs.

**Comment by nick-c-liu** [comment]
fixed in [123b2e9](https://github.com/osome-iu/top-FIBers/pull/22/commits/123b2e9e6e99d568ff9d84111fb7a1b18c84dee1)
