### ISSUE TITLE
Automatic Zenodo Backup

### ISSUE THREAD

**Issue by mr-devs** [osome-iu/top-FIBers#3]
Need to figure out how to automate the Zenodo backup of data files and iffy files created each month by this project.

- [x] Nick was going to try and pick this up from what Matt had started but I cannot add him to the assignees list because he is not an organization member. Let's all try to remember to add him to this issue once he is added to the organization.

#### Helpful information:
- See: https://developers.zenodo.org/?python#quickstart-upload
- Matt created dedicated Top FIBers API keys for this project
    - Nick/Pasan have access to Zenodo API keys in the Top FIBers slack channel
    - These can also be accessed (or updated/refreshed) on Zenodo. See the [Truthy Accounts page](https://github.iu.edu/truthy-team/truthy/wiki/Truthy-Team-Accounts) for login information to Zenodo and to update the API key
- We have already created records that exist within the OSoMe Zenodo Community
    - Forever Zenodo (cannot be deleted): https://zenodo.org/record/7905198
    - Sandback Zenodo (for testing!): https://sandbox.zenodo.org/record/1199606
- You can see the test code that Matt began to develop but did not finish in the  `zenodo_backup` branch of the old repo that Matt created (see [this](https://github.com/mr-devs/top-FIBers/tree/zenodo_backup/scripts/data_backup))

**Comment by nick-c-liu** [comment]
Currently the script would take an `ACCESS_TOKEN`, a Zenodo DOI's `conceptrecid` (10.5281/zenodo.`6423361`), and a list of file names to update the files. Now working on auto detecting the file changes and better error handling.

**Comment by nick-c-liu** [comment]
latest code detects local and remote differences and update accordingly with decent error handling.

rename to `.py` ☞ [zeondo_updatefiles.txt](https://github.com/osome-iu/top-FIBers/files/11877791/zeondo_updatefiles.txt)

**Comment by mr-devs** [comment]
Hey @Nick-the-freak I am a little confused by this .txt file, since it seems like a python script. Do you think it is working and is ready to be put into the pipeline?
