### ISSUE TITLE
Update link: architechture.md 

### ISSUE THREAD

**Issue by mr-devs** [osome-iu/top-FIBers#4]
https://github.com/osome-iu/top-FIBers/blob/c4019e40df540ee85e5d0a47779a93a28c6a361d/docs/code/architecture.md?plain=1#L13

This line still references Matt's repository.

Please make sure to update the last date updated in the yaml as well.

**Comment by pasan04** [comment]
I updated this.

**Comment by mr-devs** [comment]
Thanks, @pasan04.

It looks like you only updated the first one but there are still some links that point to the old repository. Please check and update when you can.

There are I think three links but please check them all.

**Comment by pasan04** [comment]
Sorry for it. I updated it now. I will check again other ones also now.
