### ISSUE TITLE
Add Zenodo data link to FAQ

### ISSUE THREAD

**Issue by mr-devs** [osome-iu/top-FIBers#9]
@pasan04 whenever you have a chance can you please add a section to the FAQ that looks like the below? Feel free to do this next week.

---

Question: Do you make the Top FIBer data public? 
Section text: Yes! We upload the dataset to Zenodo which you can find here: [https://doi.org/10.5281/zenodo.7905197](https://doi.org/10.5281/zenodo.7905197).

---

The question would be part of the list of questions at the top of the FAQ page and also the bolded title for that section.

Make sure to use that link as it will always resolve to the latest version. Thanks!

**Comment by pasan04** [comment]
Just updated the dashboard FAQ with this section.
